/**
 * Enumeration of U.S. States and the District of Columbia, using their official
 * two-letter postal codes as values. Keys use the full state name in PascalCase
 * for clarity and type safety..
 *
 * @see https://www.census.gov/library/reference/code-lists/ansi/ansi-codes-for-states.html
 */
export enum UsaState {
	Alabama = "AL",
	Alaska = "AK",
	Arizona = "AZ",
	Arkansas = "AR",
	California = "CA",
	Colorado = "CO",
	Connecticut = "CT",
	Delaware = "DE",
	Florida = "FL",
	Georgia = "GA",
	Hawaii = "HI",
	Idaho = "ID",
	Illinois = "IL",
	Indiana = "IN",
	Iowa = "IA",
	Kansas = "KS",
	Kentucky = "KY",
	Louisiana = "LA",
	Maine = "ME",
	Maryland = "MD",
	Massachusetts = "MA",
	Michigan = "MI",
	Minnesota = "MN",
	Mississippi = "MS",
	Missouri = "MO",
	Montana = "MT",
	Nebraska = "NE",
	Nevada = "NV",
	NewHampshire = "NH",
	NewJersey = "NJ",
	NewMexico = "NM",
	NewYork = "NY",
	NorthCarolina = "NC",
	NorthDakota = "ND",
	Ohio = "OH",
	Oklahoma = "OK",
	Oregon = "OR",
	Pennsylvania = "PA",
	RhodeIsland = "RI",
	SouthCarolina = "SC",
	SouthDakota = "SD",
	Tennessee = "TN",
	Texas = "TX",
	Utah = "UT",
	Vermont = "VT",
	Virginia = "VA",
	Washington = "WA",
	WashingtonDc = "DC",
	WestVirginia = "WV",
	Wisconsin = "WI",
	Wyoming = "WY",
}
export default UsaState;
